---
- name: Add ppa Repository
  become: yes
  become_user: root
  apt_repository: repo=ppa:ondrej/{{ php.ppa }}

- name: Update apt
  become: yes
  become_user: root
  apt: update_cache=yes

- name: Install php 5.6
  become: yes
  become_user: root
  apt: pkg=php5.6 state=latest

- name: Install PHP Packages
  become: yes
  become_user: root
  apt: pkg={{ item }} state=latest
  with_items:
    - php5.6-cli
    - php5.6-intl
    - php5.6-mcrypt
    - php5.6-curl
    - php5.6-mongo
    - php5.6-mongodb
    - php5.6-mbstring
    - php5.6-dom
- include: configure.yml
