---
- name: Install Apache
  become: yes
  become_user: root
  apt: pkg=apache2 state=latest

- name: Install Apache Modules
  apache2_module: state=present name={{ item }}
  notify: restart apache
  with_items:
    - rewrite
    - vhost_alias
    - headers
    - expires
    - filter

- shell: apache2 -v
  register: apache_version

- name: Change default apache2.4 site
  become: yes
  become_user: root
  template: src=vhost24.conf.tpl dest=/etc/apache2/sites-available/000-default.conf
  notify: restart apache

- name: Change Apache's default listening port
  become: yes
  become_user: root
  template: src=ports.conf.tpl dest=/etc/apache2/ports.conf
  notify: restart apache
